#  #
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation; either version 2
#   of the License, or (at your option) any later version.
#  #
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#  #
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#  #
#
#  <pep8 compliant>

class SHAPELY_TYPE:
    point = "Point"
    multiPoint = "MultiPoint"
    lineString = "LineString"
    multiLineString = "MultiLineString"
    polygon = "Polygon"
    multiPolygon = "MultiPolygon"
    none = "None"

# constants
ADDON_NAME = "Google-Earth-Decoder-Optimization-Tools"

CEND = "\033[0m"
BOLD = "\033[01m"
CRED = "\033[31m"
CGREEN = "\033[32m"
CORANGE = "\033[38;5;214m"
CREDBG = "\033[41m"
CGREENBG = "\033[6;30;42m"
CORANGEBG = "\033[6;30;43m"
OK = "OK"
KO = "KO"
EOL = "\n"
GLOBAL_SETTINGS_TEMPLATE_FILE = "global_settings.ini"
PROJECT_SETTINGS_TEMPLATE_FILE = "project_settings.ini"
INI_FILE = "GEDOT.ini"
EARTH_RADIUS = 6371010

ROAD_LANE_WIDTH = 3.0

PNG_TEXTURE_FORMAT = "png"
JPG_TEXTURE_FORMAT = "jpg"

INI_FILE_EXT = ".ini"
ZIP_FILE_EXT = ".zip"
TXT_FILE_EXT = ".txt"
WHL_FILE_EXT = ".whl"
XML_FILE_EXT = ".xml"
GLTF_FILE_EXT = ".gltf"
BIN_FILE_EXT = ".bin"
DBF_FILE_EXT = ".dbf"
SHP_FILE_EXT = ".shp"
SHX_FILE_EXT = ".shx"
OSM_FILE_EXT = ".osm"
OBJ_FILE_EXT = ".obj"
POS_FILE_EXT = ".pos"
PNG_FILE_EXT = "." + PNG_TEXTURE_FORMAT
JPG_FILE_EXT = "." + JPG_TEXTURE_FORMAT

XML_FILE_PATTERN = "*" + XML_FILE_EXT
GLTF_FILE_PATTERN = "*" + GLTF_FILE_EXT
BIN_FILE_PATTERN = "*" + BIN_FILE_EXT
DBF_FILE_PATTERN = "*" + DBF_FILE_EXT
SHP_FILE_PATTERN = "*" + SHP_FILE_EXT
SHX_FILE_PATTERN = "*" + SHX_FILE_EXT
OSM_FILE_PATTERN = "*" + OSM_FILE_EXT
JPG_FILE_PATTERN = "*" + JPG_FILE_EXT
PNG_FILE_PATTERN = "*" + PNG_FILE_EXT
OBJ_FILE_PATTERN = "*" + OBJ_FILE_EXT

ENCODING = "utf-8"

XML_HEADER = '<?xml version="1.0"?>'

CLEAR_CONSOLE_CMD = "cls"

PYTHON_COMPIL_OPTION = "exec"

PILLOW_LIB = "Pillow"
NUMPY_LIB = "numpy"
NUMPY_LIB_VERSION = "1.24"
OSMNX_LIB = "osmnx"
OSMNX_LIB_VERSION = "1.3.0"
NETWORKX_LIB = "networkx"
RTREE_LIB = "rtree"
MATPLOTLIB_LIB = "matplotLib"
PANDAS_LIB = "pandas"
GEOPANDAS_LIB = "geopandas"
SCIPY_LIB = "scipy"
SHAPELY_LIB = "shapely"
PYGEODESY_LIB = "pygeodesy"
TORCH_LIB = "torch"
SAMGEO_LIB = "segment-geospatial"
ALTERNATE_PYTHON_LIB_REPO = "http://www.xavierdupre.fr/enseignement/setup/"
BLENDERGIS_ADDON = "BlenderGIS-228"
BLENDERGIS_GITHUB_DOWNLOAD_REPO = "https://github.com/domlysz/BlenderGIS/archive/refs/tags/"
BLENDERGIS_ADDON_RELEASE = "228"
GDAL_LIB_PREFIX = "GDAL-3.4.3"
FIONA_LIB_PREFIX = "Fiona-1.8.21"
WIN32_SUFFIX = "win32"
WIN64_SUFFIX = "win_amd64"
CRITICAL_LOG_LEVEL = "CRITICAL"
EPSG_WGS84 = "EPSG:4326"
DEFAULT_OVERPASS_API_URI = "https://overpass-api.de/api"

LAND_MASS_REPO = "https://osmdata.openstreetmap.de/download/"
LAND_MASS_ARCHIVE = "land-polygons-split-4326.zip"

CONSTANTS_FOLDER = "constants"
UTILS_FOLDER = "utils"
SCRIPT_FOLDER = "scripts"
UI_FOLDER = "UI"
TEXTURE_FOLDER = "texture"
CLEANUP_3D_DATA_BACKUP_FOLDER = "cleanup_3d_data"
RESIZE_SCENERY_TEXTURES_BACKUP_FOLDER = "resize_scenery_textures"

SCRIPT_PREFIX = "_script"
COLLIDER_SUFFIX = "_collider"
GEOCODE_SUFFIX = "_geocode"
HEIGHT_MAP_PREFIX = "height_map_"
LANDMARK_PREFIX = "landmark_"

RESOURCE_FOLDER = "resource"
CONFIG_TEMPLATES_FOLDER = RESOURCE_FOLDER + "\\" + "config"
TEMPLATES_FOLDER = RESOURCE_FOLDER + "\\" + "templates"
THUMBNAIL_FOLDER = RESOURCE_FOLDER + "\\" + "thumbnail"
SHAPE_TEMPLATES_FOLDER = RESOURCE_FOLDER + "\\" + "shapes"
GEOIDS_DATASET_FOLDER = RESOURCE_FOLDER + "\\" + "geoids"
LIGHT_MODELS_FOLDER = RESOURCE_FOLDER + "\\" + "lights"

BUSINESS_JSON_TEMPLATE = "Business.json"
PACKAGE_DEFINITIONS_TEMPLATE = "package-definition" + XML_FILE_EXT
PROJECT_DEFINITION_TEMPLATE = "project-definition" + XML_FILE_EXT
THUMBNAIL_PICTURE_TEMPLATE = "Thumbnail" + JPG_FILE_EXT
OSM_LAND_SHAPEFILE = "land_polygons" + SHP_FILE_EXT
EGM2008_5_DATASET = "egm2008-5.pgm"

PROJECT_DEFINITION_TEMPLATE_PATH = TEMPLATES_FOLDER + "\\" + PROJECT_DEFINITION_TEMPLATE
BUSINESS_JSON_TEMPLATE_PATH = TEMPLATES_FOLDER + "\\" + BUSINESS_JSON_TEMPLATE
PACKAGE_DEFINITIONS_TEMPLATE_PATH = TEMPLATES_FOLDER + "\\" + PACKAGE_DEFINITIONS_TEMPLATE
THUMBNAIL_PICTURE_TEMPLATE_PATH = THUMBNAIL_FOLDER + "\\" + THUMBNAIL_PICTURE_TEMPLATE

LILY_TEXTURE_PACKER_ADDON = "LilyTexturePacker"

MAX_PHOTOGRAMMETRY_LOD = 23
LESS_DETAILED_LODS_LIMIT = 18

TARGET_MIN_SIZE_VALUE_PROPERTY_PREFIX = "target_min_size_value_"

LIGHT_WARM_GUID = "{DB0162E7-91A2-46E9-81B7-55A66CEC8839}"
LIGHT_COLD_GUID = "{8EF4C350-65F3-455B-AF52-64511D7F9510}"
LIGHT_100_BLUE_GUID = "{6C2F47E4-2A51-4EF5-A2C3-A321C21A950E}"
LIGHT_500_BLUE_GUID = "{F03FDFEA-C514-4133-9030-625D31E372FC}"
LIGHT_1000_BLUE_GUID = "{4AB2D6EA-6515-4A23-AAA8-04C7B5B63065}"
LIGHT_100_GREEN_GUID = "{54D5862A-73BE-42FF-A297-D1031598C997}"
LIGHT_500_GREEN_GUID = "{F5DA7287-9198-443D-9D33-4A99AAC4B417}"
LIGHT_1000_GREEN_GUID = "{3E692280-BE9B-4CFD-999C-3F650A9289DD}"
LIGHT_100_SOFT_GREEN_GUID = "{5715DF05-56F5-45C5-B2C7-175C003B380F}"
LIGHT_500_SOFT_GREEN_GUID = "{5722552F-5471-403C-8543-B2DD0430B9ED}"
LIGHT_1000_SOFT_GREEN_GUID = "{D31D32D6-2A1D-4CA1-8B93-9E75C99200C6}"
LIGHT_100_WHITE_GUID = "{1FB25231-CBEF-41FD-9D6D-6CF50E2F24EE}"
LIGHT_500_WHITE_GUID = "{43F08510-06B6-41AC-80BE-62A0DB23842C}"
LIGHT_1000_WHITE_GUID = "{2C9CFD05-52BC-4BCB-AA4B-D9C6963065BD}"
LIGHT_100_MINT_GREEN_GUID = "{8E857230-1455-40F3-B4E5-4316F403FD59}"
LIGHT_500_MINT_GREEN_GUID = "{E66F0EFB-B21B-4D58-B1A1-0232DDE9C713}"
LIGHT_1000_MINT_GREEN_GUID = "{FE235DDB-0419-4E13-BC52-D17778EC5115}"
LIGHT_100_ORANGE_GUID = "{A2B743C6-AF87-4724-90AF-1E81AD437DB0}"
LIGHT_500_ORANGE_GUID = "{886D41AC-BD53-4B7A-8F5D-BB8734103959}"
LIGHT_1000_ORANGE_GUID = "{5E6E2E59-CAEE-475A-AABD-4AAC65080B29}"
LIGHT_100_PINK_GUID = "{CA3EC544-532C-4EC9-8A9A-AE64CE18202B}"
LIGHT_500_PINK_GUID = "{4FB7F83A-5892-46F7-8E9F-B088D5DCB605}"
LIGHT_1000_PINK_GUID = "{53359DFF-193F-44FE-9F25-2B3298F8E523}"
LIGHT_100_RED_GUID = "{B2ED3D3F-0E5B-4370-9045-DDA34FC0BEB4}"
LIGHT_500_RED_GUID = "{20DE7319-60F4-49DA-AC4D-B29F9D73AC77}"
LIGHT_1000_RED_GUID = "{7E393701-35F5-45E3-BCDA-6EF0D7ED1AE2}"
LIGHT_100_SKY_BLUE_GUID = "{E4FD12C9-A481-4380-B114-D6C9B57D205B}"
LIGHT_500_SKY_BLUE_GUID = "{D2116422-2D39-4C00-95F9-D389B9B88F47}"
LIGHT_1000_SKY_BLUE_GUID = "{6DC0CDB4-F096-4CF5-A9C9-765AB59A06A2}"
LIGHT_100_PURPLE_GUID = "{B9CF1AE5-9B3F-48CE-A52F-6813DC5399F2}"
LIGHT_500_PURPLE_GUID = "{5F745C2D-4537-4966-854E-B51A3E36D0FF}"
LIGHT_1000_PURPLE_GUID = "{4A3CBA6B-E55F-4B75-A270-594D88D6427E}"
LIGHT_100_YELLOW_GUID = "{C8197456-99DF-40C1-AB82-D991F22797B9}"
LIGHT_500_YELLOW_GUID = "{67D2E161-69EA-46AE-842F-258706285F92}"
LIGHT_1000_YELLOW_GUID = "{0301375F-2CB4-49E9-80E0-8ABEFBA0FDDE}"

LIGHT_WARM_DISPLAY_NAME = "Warm light"
LIGHT_COLD_DISPLAY_NAME = "Cold light"
LIGHT_100_BLUE_DISPLAY_NAME = "Blue light (100W)"
LIGHT_500_BLUE_DISPLAY_NAME = "Blue light (500W)"
LIGHT_1000_BLUE_DISPLAY_NAME = "Blue light (1000W)"
LIGHT_100_GREEN_DISPLAY_NAME = "Green light (100W)"
LIGHT_500_GREEN_DISPLAY_NAME = "Green light (500W)"
LIGHT_1000_GREEN_DISPLAY_NAME = "Green light (1000W)"
LIGHT_100_SOFT_GREEN_DISPLAY_NAME = "Soft green light (100W)"
LIGHT_500_SOFT_GREEN_DISPLAY_NAME = "Soft green light (500W)"
LIGHT_1000_SOFT_GREEN_DISPLAY_NAME = "Soft green light (1000W)"
LIGHT_100_WHITE_DISPLAY_NAME = "White light (100W)"
LIGHT_500_WHITE_DISPLAY_NAME = "White light (500W)"
LIGHT_1000_WHITE_DISPLAY_NAME = "White light (1000W)"
LIGHT_100_MINT_GREEN_DISPLAY_NAME = "Mint green light (100W)"
LIGHT_500_MINT_GREEN_DISPLAY_NAME = "Mint green light (500W)"
LIGHT_1000_MINT_GREEN_DISPLAY_NAME = "Mint green light (1000W)"
LIGHT_100_ORANGE_DISPLAY_NAME = "Orange light (100W)"
LIGHT_500_ORANGE_DISPLAY_NAME = "Orange light (500W)"
LIGHT_1000_ORANGE_DISPLAY_NAME = "Orange light (1000W)"
LIGHT_100_PINK_DISPLAY_NAME = "Pink light (100W)"
LIGHT_500_PINK_DISPLAY_NAME = "Pink light (500W)"
LIGHT_1000_PINK_DISPLAY_NAME = "Pink light (1000W)"
LIGHT_100_RED_DISPLAY_NAME = "Red light (100W)"
LIGHT_500_RED_DISPLAY_NAME = "Red light (500W)"
LIGHT_1000_RED_DISPLAY_NAME = "Red light (1000W)"
LIGHT_100_SKY_BLUE_DISPLAY_NAME = "Sky blue light (100W)"
LIGHT_500_SKY_BLUE_DISPLAY_NAME = "Sky blue light (500W)"
LIGHT_1000_SKY_BLUE_DISPLAY_NAME = "Sky blue light (1000W)"
LIGHT_100_PURPLE_DISPLAY_NAME = "Purple light (100W)"
LIGHT_500_PURPLE_DISPLAY_NAME = "Purple light (500W)"
LIGHT_1000_PURPLE_DISPLAY_NAME = "Purple light (1000W)"
LIGHT_100_YELLOW_DISPLAY_NAME = "Yellow light (100W)"
LIGHT_500_YELLOW_DISPLAY_NAME = "Yellow light (500W)"
LIGHT_1000_YELLOW_DISPLAY_NAME = "Yellow light (1000W)"

LIGHT_HEADING = "-179.999995"

PITCH_TERRAFORM_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_pitch_terraform_polygons"
PITCH_TERRAFORM_POLYGON_NAME_PREFIX = "pt"
AMENITY_TERRAFORM_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_amenity_terraform_polygons"
AMENITY_TERRAFORM_POLYGON_NAME_PREFIX = "at"
CONSTRUCTION_TERRAFORM_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_construction_terraform_polygons"
CONSTRUCTION_TERRAFORM_POLYGON_NAME_PREFIX = "ct"
INDUSTRIAL_TERRAFORM_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_industrial_terraform_polygons"
INDUSTRIAL_TERRAFORM_POLYGON_NAME_PREFIX = "it"
FORESTS_VEGETATION_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_forests_vegetation_polygons"
FORESTS_VEGETATION_POLYGON_NAME_PREFIX = "ft"
WOODS_VEGETATION_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_woods_vegetation_polygons"
WOODS_VEGETATION_POLYGON_NAME_PREFIX = "wt"
GOLF_TERRAFORM_POLYGONS_DISPLAY_NAME = "GEDOT_generated_golf_terraform_polygons"
GOLF_TERRAFORM_POLYGON_NAME_PREFIX = "gt"
EXCLUSION_BUILDING_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_exclusion_building_polygons"
EXCLUSION_BUILDING_POLYGON_NAME_PREFIX = "be"
EXCLUSION_VEGETATION_POLYGONS_GROUP_DISPLAY_NAME = "GEDOT_generated_exclusion_vegetation_polygons"
EXCLUSION_VEGETATION_POLYGON_NAME_PREFIX = "ve"
HEIGHT_MAPS_GROUP_DISPLAY_NAME = "GEDOT_generated_height_maps"
HEIGHT_MAP_GROUP_DISPLAY_NAME = "GEDOT_generated_height_map"
HEIGHT_MAP_NAME_PREFIX = "hm"
LIGHTS_GROUP_DISPLAY_NAME = "GEDOT_generated_lights"
LIGHT_NAME_PREFIX = "l"

PROJECT_INI_SECTION = "PROJECT"
MERGE_INI_SECTION = "MERGE"
TILE_INI_SECTION = "TILE"
LODS_INI_SECTION = "LODS"
OSM_INI_SECTION = "OPENSTREETMAP"
GEOCODE_INI_SECTION = "GEOCODE"
ALTITUDE_ADJUSTMENT_INI_SECTION = "ALTITUDE_ADJUSTMENT"
TEXTURES_INI_SECTION = "TEXTURES"
MSFS_SDK_INI_SECTION = "MSFS_SDK"
BUILD_INI_SECTION = "AUTOMATIC_BUILD"
COMPRESSONATOR_INI_SECTION = "COMPRESSONATOR"
BACKUP_INI_SECTION = "BACKUP"
PYTHON_INI_SECTION = "PYTHON"

NONE_ICON = "NONE"
FILE_FOLDER_ICON="FILE_FOLDER"
FILE_TICK_ICON = "FILE_TICK"
FILE_REFRESH_ICON = "FILE_REFRESH"
INFO_ICON = "INFO"
ADD_ICON = "ADD"
REMOVE_ICON = "REMOVE"

DUMMY_OBJECT = "dummy"

OSM_MATERIAL_NAME = "OSM_material"

WAY_OSM_PREFIX = "W"
RELATION_OSM_PREFIX = "R"
NODE_OSM_PREFIX = "N"

LANDUSE_OSM_KEY = "landuse"
LEISURE_OSM_KEY = "leisure"
NATURAL_OSM_KEY = "natural"
NATURAL_WATER_OSM_KEY = "natural_water"
WATER_OSM_KEY = "water"
WATERWAY_OSM_KEY = "waterway"
AEROWAY_OSM_KEY = "aeroway"
BOUNDARY_OSM_KEY = "boundary"
BOUNDING_BOX_OSM_KEY = "box"
RESIDENTIAL_OSM_KEY = "residential"
INDUSTRIAL_OSM_KEY = "industrial"
AMENITY_OSM_KEY = "amenity"
BUILDING_OSM_KEY = "building"
ROCKS_OSM_KEY = "rocks"
ROAD_OSM_KEY = "highway"
RAILWAY_OSM_KEY = "railway"
SERVICE_OSM_KEY = "service"
MAN_MADE_OSM_KEY = "man_made"
GROUND_OSM_KEY = "ground"
PITCH_OSM_KEY = "pitch"
CONSTRUCTION_OSM_KEY = "construction"
GRASS_OSM_KEY = "grass"
GOLF_OSM_KEY = "golf"
PARK_OSM_KEY = "park"
WALL_OSM_KEY = "wall"
NOT_SHORE_WATER_OSM_KEY = "not_shore",
NOT_EXCLUSION_BUILDING_OSM_KEY = "not_exclusion_building",
ROAD_REMOVAL_LANDUSE_OSM_KEY = "road_removal_landuse"
ROAD_REMOVAL_NATURAL_OSM_KEY = "road_removal_natural"
ELEMENT_TY_OSM_KEY = "element_ty"
OSMID_OSM_KEY = "osmid"
LANES_OSM_KEY = "lanes"
ONEWAY_OSM_KEY = "oneway"
BARRIER_OSM_KEY = "barrier"
LAT_OSM_KEY = "lat"
LON_OSM_KEY = "lon"

FOREST_OSM_TAG = "forest"
NATURE_RESERVE_OSM_TAG = "nature_reserve"
FARMLAND_OSM_TAG = "farmland"
MEADOW_OSM_TAG = "meadow"
VINEYARD_OSM_TAG = "vineyard"
PARK_OSM_TAG = "park"
PLAYGROUND_OSM_TAG = "playground"
PITCH_OSM_TAG = "pitch"
GRASS_OSM_TAG = "grass"
WOOD_OSM_TAG = "wood"
BAY_OSM_TAG = "bay"
WATER_OSM_TAG = "water"
RIVER_OSM_TAG = "river"
STREAM_OSM_TAG = "stream"
SEA_OSM_TAG = "sea"
LAKE_OSM_TAG = "lake"
BEACH_OSM_TAG = "beach"
GRASSLAND_OSM_TAG = "grassland"
SCRUB_OSM_TAG = "scrub"
POND_OSM_TAG = "pond"
WASTEWATER_OSM_TAG = "wastewater"
RESERVOIR_OSM_TAG = "reservoir"
CANAL_OSM_TAG = "canal"
BASIN_OSM_TAG = "basin"
ALLOTMENTS_OSM_TAG = "allotment"
HEATH_OSM_TAG = "heath"
WETLAND_OSM_TAG = "wetland"
BARE_ROCK_OSM_TAG = "bare_rock"
CLIFF_OSM_TAG = "cliff"
FELL_OSM_TAG = "fell"
COASTLINE_OSM_TAG = "coastline"
GEOMETRY_OSM_COLUMN = "geometry"
MARITIME_OSM_KEY = "maritime"
NATIONAL_PARK_OSM_KEY = "national_park"
PROTECTED_AREA_OSM_KEY = "protected_area"
MARINA_OSM_TAG = "marina"
PIER_OSM_TAG = "pier"
HEIGHT_OSM_TAG = "height"
TREE_TAG = "tree"
TREE_ROW_TAG = "tree_row"
ORCHARD_OSM_TAG = "orchard"
BRIDGE_OSM_TAG = "bridge"
TUNNEL_OSM_TAG = "tunnel"
SEAMARK_TYPE_OSM_TAG = "seamark:type"
SLIPWAY_OSM_TAG = "slipway"
PEDESTRIAN_OSM_TAG = "pedestrian"
FOOTWAY_OSM_TAG = "footway"
PATH_OSM_TAG = "path"
FAIRWAY_OSM_TAG = "fairway"
AREA_OSM_TAG = "area"
CONSTRUCTION_OSM_TAG = "construction"
RESIDENTIAL_OSM_TAG = "residential"
INDUSTRIAL_OSM_TAG = "industrial"
DISPLAY_NAME_OSM_TAG = "display_name"
NAME_OSM_TAG = "name"
WALL_OSM_TAG = "wall"
CASTLE_WALL_OSM_TAG = "castle_wall"
WATERMILL_OSM_TAG = "watermill"
TOWER_OSM_TAG = "tower"
MAST_OSM_TAG = "mast"
BREAKWATER_OSM_TAG = "breakwater"
STORAGE_TANK_OSM_TAG = "storage_tank"
WORKS_OSM_TAG = "works"
CHIMNEY_OSM_TAG = "chimney"
OBELISK_OSM_TAG = "obelisk"
SILO_OSM_TAG = "silo"
TELESCOPE_OSM_TAG = "telescope"
WATER_TOWER_OSM_TAG = "water_tower"
OBSERVATORY_OSM_TAG = "observatory"
PROPOSED_OSM_TAG = "proposed"

AIRPORT_GEOCODE = "airport"

EXCLUSION_OSM_FILE_PREFIX = "exclusion"
ISOLATION_OSM_FILE_PREFIX = "isolation"
BOUNDING_BOX_OSM_FILE_PREFIX = "bbox"
WHOLE_WATER_OSM_FILE_PREFIX = "whole_water"
BUILDING_OSM_FILE_PREFIX = "building"
GEOCODE_OSM_FILE_PREFIX = "geocode"
LANDMARK_LOCATION_OSM_FILE_NAME = GEOCODE_OSM_FILE_PREFIX + "_landmark_location"

GEOCODE_LIGHTS_PREFIX = GEOCODE_OSM_FILE_PREFIX + "_lights"

FEET_TO_METER_RATIO = 0.3048
TILE_THICKNESS = 0.5

MOTORWAY_ROAD_TYPE = "motorway"
TRUNK_ROAD_TYPE = "trunk"
MOTORWAY_LINK_ROAD_TYPE = "motorway_link"
PRIMARY_ROAD_TYPE = "primary"
SECONDARY_ROAD_TYPE = "secondary"
TERTIARY_ROAD_TYPE = "tertiary"
RESIDENTIAL_ROAD_TYPE = "residential"
PEDESTRIAN_ROAD_TYPE = "pedestrian"
FOOTWAY_ROAD_TYPE = "footway"
CYCLEWAY_ROAD_TYPE = "cycleway"
SERVICE_ROAD_TYPE = "service"
RAILWAY_ROAD_TYPE = "railway"
PATH_ROAD_TYPE = "path"
TRACK_ROAD_TYPE = "track"

FULL_PREFIX = "full_"

POI_LANDMARK_FORMAT_TYPE = "POI"
CITY_LANDMARK_FORMAT_TYPE = "City"

STANDARD_EXCLUSION_MARGIN = 10.0

ROAD_WITH_BORDERS = [
    MOTORWAY_ROAD_TYPE,
    TRUNK_ROAD_TYPE,
    MOTORWAY_LINK_ROAD_TYPE,
    PRIMARY_ROAD_TYPE,
    SECONDARY_ROAD_TYPE,
    TERTIARY_ROAD_TYPE
]

OSM_TAGS = {
    BOUNDARY_OSM_KEY: [
        FOREST_OSM_TAG,
        MARITIME_OSM_KEY,
        NATIONAL_PARK_OSM_KEY
    ],
    LANDUSE_OSM_KEY: [
        FOREST_OSM_TAG,
        FARMLAND_OSM_TAG,
        VINEYARD_OSM_TAG,
        ALLOTMENTS_OSM_TAG,
        ORCHARD_OSM_TAG,
        MEADOW_OSM_TAG
    ],
    LEISURE_OSM_KEY: [
        NATURE_RESERVE_OSM_TAG
    ],
    NATURAL_OSM_KEY: [
        FOREST_OSM_TAG,
        WOOD_OSM_TAG,
        GRASSLAND_OSM_TAG,
        SCRUB_OSM_TAG,
        FELL_OSM_TAG
    ],
    WATER_OSM_KEY: [
        RIVER_OSM_TAG,
        STREAM_OSM_TAG,
        SEA_OSM_TAG,
        LAKE_OSM_TAG,
        WATER_OSM_KEY,
        POND_OSM_TAG,
        WASTEWATER_OSM_TAG,
        CANAL_OSM_TAG,
        BASIN_OSM_TAG,
        MARINA_OSM_TAG,
        RESERVOIR_OSM_TAG
    ],
    NATURAL_WATER_OSM_KEY: [
        BAY_OSM_TAG,
        WATER_OSM_TAG,
        RIVER_OSM_TAG,
        STREAM_OSM_TAG,
        SEA_OSM_TAG,
        WETLAND_OSM_TAG,
        BEACH_OSM_TAG
    ],
    WATERWAY_OSM_KEY: [
        RIVER_OSM_TAG,
        CANAL_OSM_TAG
    ],
    AEROWAY_OSM_KEY: [],
    ROCKS_OSM_KEY: [
        BARE_ROCK_OSM_TAG,
        CLIFF_OSM_TAG
    ],
    PITCH_OSM_KEY: [
        PITCH_OSM_TAG
    ],
    CONSTRUCTION_OSM_KEY: [
        CONSTRUCTION_OSM_TAG
    ],
    RESIDENTIAL_OSM_KEY: [
        RESIDENTIAL_OSM_TAG
    ],
    INDUSTRIAL_OSM_KEY: [
        INDUSTRIAL_OSM_TAG
    ],
    GRASS_OSM_KEY: [
        GRASS_OSM_TAG
    ],
    GOLF_OSM_KEY: [
        FAIRWAY_OSM_TAG
    ],
    PARK_OSM_KEY: [
        PARK_OSM_TAG
    ],
    NOT_SHORE_WATER_OSM_KEY: [
        WATER_OSM_KEY,
        POND_OSM_TAG,
        WASTEWATER_OSM_TAG,
        CANAL_OSM_TAG,
        BASIN_OSM_TAG,
        RESERVOIR_OSM_TAG,
        WETLAND_OSM_TAG,
        RIVER_OSM_TAG,
        LAKE_OSM_TAG,
        STREAM_OSM_TAG
    ],
    NOT_EXCLUSION_BUILDING_OSM_KEY: [
        WATER_OSM_KEY,
        POND_OSM_TAG,
        WASTEWATER_OSM_TAG,
        CANAL_OSM_TAG,
        BASIN_OSM_TAG,
        RESERVOIR_OSM_TAG,
        WETLAND_OSM_TAG
    ],
    BARRIER_OSM_KEY: [
        WALL_OSM_TAG
    ],
    MAN_MADE_OSM_KEY: [
        WATERMILL_OSM_TAG,
        TOWER_OSM_TAG,
        MAST_OSM_TAG,
        BREAKWATER_OSM_TAG,
        STORAGE_TANK_OSM_TAG,
        WORKS_OSM_TAG,
        CHIMNEY_OSM_TAG,
        OBELISK_OSM_TAG,
        SILO_OSM_TAG,
        TELESCOPE_OSM_TAG,
        WATER_TOWER_OSM_TAG,
        OBSERVATORY_OSM_TAG,
        PIER_OSM_TAG,
        BRIDGE_OSM_TAG
    ],
    ROAD_REMOVAL_LANDUSE_OSM_KEY: [
        FOREST_OSM_TAG,
        NATURE_RESERVE_OSM_TAG
    ],
    ROAD_REMOVAL_NATURAL_OSM_KEY: [
        FOREST_OSM_TAG,
        WOOD_OSM_TAG
    ],
}

